In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [11]:
arr2=np.array([1,2,3,4,5])
arr2.reshape((1,5))

array([[1, 2, 3, 4, 5]])

In [12]:
arr2

array([1, 2, 3, 4, 5])

In [15]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [5]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
arr=np.array([[1,2,3],[4,5,6]])

print(f'Shape: {arr.shape}')
print(f'Number of Dimensions: {arr.ndim}')
print(f'Size (nummber of elements): {arr.size}')
print(f'Data Type: {arr.dtype}')
print(f'Item size: {arr.itemsize}')

Shape: (2, 3)
Number of Dimensions: 2
Size (nummber of elements): 6
Data Type: int32
Item size: 4


In [14]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print('Addition' ,arr1+arr2)
print('Subtraction: ',arr1-arr2)
print('Multiplication: ',arr1*arr2)
print('Subtraction: ',arr1/arr2)

Addition [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Subtraction:  [0.1 0.1 0.1 0.1 0.1]


In [16]:
arr=np.array([1,2,3,4,5,6])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [19]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [34]:
arr[1:]=100
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [35]:
data=np.array([1,2,3,4,5])

In [36]:
mean=np.mean(data)
std_dev=np.std(data)

In [37]:
normalized_data=(data-mean)/std_dev
print('Normalized Data: ',normalized_data)

Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [38]:
data=np.array([1,2,3,4,5,6,7,8])

In [ ]:
data[(data>5)&(data<=8)]

array([6, 7, 8])

: 